version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: ${APP_NAME}-web
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - .:/app
    networks:
      - microservice

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: ${APP_NAME}-php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - .:/app
    networks:
      - microservice

  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - microservice

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}-phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=2048
    depends_on:
      - mysql
    networks:
      - microservice

networks:
  microservice:
    driver: bridge

volumes:
  mysql_data: {}
